# Generated by Django 2.2.3 on 2020-02-24 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField()),
                ('score', models.IntegerField()),
            ],
            options={
                'ordering': 'score',
            },
        ),
    ]
